
version: '3.8'

services:
  frontend:
    image: nginx:latest
    container_name: dazzle-store-studio-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: dazzle-store-studio-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=supersecret
      - DB_NAME=eliteshop
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: dazzle-store-studio-db
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=eliteshop
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
